[project]
site_name = "NC"
site_url = "https://nclang.org"
site_description = "A new language I'm working on"
site_author = "noClaps"
docs_dir = "design"
repo_url = "https://github.com/noClaps/nc"
repo_name = "noClaps/nc"
extra_javascript = [
    "javascripts/katex.js",
    "https://unpkg.com/katex@0/dist/katex.min.js",
    "https://unpkg.com/katex@0/dist/contrib/auto-render.min.js"
]
extra_css = [
    "https://unpkg.com/katex@0/dist/katex.min.css"
]

[project.theme]
font = false
language = "en"
features = [
    "navigation.sections",
    "navigation.footer",
    "navigation.top",
]

# Palette toggle for automatic mode
[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle.icon = "lucide/sun-moon"
toggle.name = "Switch to light mode"
primary = "orange"
accent = "orange"

# Palette toggle for light mode
[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"
primary = "orange"
accent = "orange"

# Palette toggle for dark mode
[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to system preference"
primary = "orange"
accent = "orange"

[project.markdown_extensions.admonition]

[project.markdown_extensions.pymdownx.arithmatex]
generic = true

[project.markdown_extensions.pymdownx.superfences]

[project.markdown_extensions.pymdownx.highlight]
